### ISSUE TITLE
Algo server active notification breaks golangLib

### ISSUE THREAD

**Issue by JacobPlaster** [bitfinexcom/bfx-hf-algo-server#7]
When the algo server is active a notification is broadcasted which does not correctly fit the schema of the bitfinex api notification. This causes for go (which expects an exact type schema) to break:

```
Incoming: [1.559795887973e+12 ucm-hb 1.559795890329e+12 <nil> map[] <nil> <nil> <nil>]

panic: interface conversion: interface {} is map[string]interface {}, not []interface {}

goroutine 59 [running]:
github.com/bitfinexcom/bitfinex-api-go/v2.NewNotificationFromRaw(0xc0003c6000, 0x8, 0x8, 0xc0000ba2a0, 0x194, 0x0)
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/types.go:1257 +0xab1
github.com/bitfinexcom/bitfinex-api-go/v2/websocket.(*Client).convertRaw(0xc0001320e0, 0xc5c34e, 0x1, 0xc0003c6000, 0x8, 0x8, 0xc000329d50, 0x42ce81)
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/websocket/channels.go:347 +0x398
github.com/bitfinexcom/bitfinex-api-go/v2/websocket.(*Client).handlePrivateDataMessage(0xc0001320e0, 0xc5c34e, 0x1, 0xc0003c6000, 0x8, 0x8, 0x7d74b8, 0xc0000c2e10, 0x1c60271f89, 0xc946c0)
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/websocket/channels.go:222 +0x7b
github.com/bitfinexcom/bitfinex-api-go/v2/websocket.(*Client).handlePrivateChannel(0xc0001320e0, 0xc0000ba280, 0x3, 0x4, 0x0, 0x0)
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/websocket/channels.go:147 +0x25a
github.com/bitfinexcom/bitfinex-api-go/v2/websocket.(*Client).handleChannel(0xc0001320e0, 0xc00047d200, 0x45, 0x600, 0x1, 0x1)
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/websocket/channels.go:53 +0x514
github.com/bitfinexcom/bitfinex-api-go/v2/websocket.(*Client).handleMessage(0xc0001320e0, 0xc00047d200, 0x45, 0x600, 0x1, 0x0)
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/websocket/client.go:447 +0x26e
github.com/bitfinexcom/bitfinex-api-go/v2/websocket.(*Client).listenUpstream(0xc0001320e0, 0x98ef40, 0xc0000c2eb0)
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/websocket/client.go:369 +0x14c
created by github.com/bitfinexcom/bitfinex-api-go/v2/websocket.(*Client).reset
        /mnt/c/Users/jacob/Documents/go/pkg/mod/github.com/bitfinexcom/bitfinex-api-go@v0.0.0-20190416080155-c16c61b288fb/v2/websocket/client.go:307 +0xcb
```

Goland notification parsing function:

```
func NewNotificationFromRaw(raw []interface{}) (o *Notification, err error) {
	fmt.Println(raw)
	if len(raw) < 8 {
		return o, fmt.Errorf("data slice too short for notification: %#v", raw)
	}

	o = &Notification{
		MTS:       i64ValOrZero(raw[0]),
		Type:      sValOrEmpty(raw[1]),
		MessageID: i64ValOrZero(raw[2]),
		//NotifyInfo: raw[4],
		Code:   i64ValOrZero(raw[5]),
		Status: sValOrEmpty(raw[6]),
		Text:   sValOrEmpty(raw[7]),
	}

	// raw[4] = notify info
	var nraw []interface{}
	if raw[4] != nil {
		nraw = raw[4].([]interface{})
		switch o.Type {
		case "on-req":
			on, err := NewOrderFromRaw(nraw)
			if err != nil {
				return o, err
			}
			orderNew := OrderNew(*on)
			o.NotifyInfo = &orderNew
		case "oc-req":
			oc, err := NewOrderFromRaw(nraw)
			if err != nil {
				return o, err
			}
			orderCancel := OrderCancel(*oc)
			o.NotifyInfo = &orderCancel
		case "fon-req":
			fon, err := NewOfferFromRaw(nraw)
			if err != nil {
				return o, err
			}
			fundingOffer := FundingOfferNew(*fon)
			o.NotifyInfo = &fundingOffer
		case "foc-req":
			foc, err := NewOfferFromRaw(nraw)
			if err != nil {
				return o, err
			}
			fundingOffer := FundingOfferCancel(*foc)
			o.NotifyInfo = &fundingOffer
		case "uca":
			o.NotifyInfo = raw[4]
		}
	}

	return
}
```

**Comment by JacobPlaster** [comment]
it expects raw[4] to be an array but gets a json map

**Comment by JacobPlaster** [comment]
Crashed my golang trading bot every time I run the dev `bfx-hf-ui` hahaha

**Comment by f3rno** [comment]
Can you patch this?

**Comment by JacobPlaster** [comment]
Ahh just read on the api docs that the 4th item in the notification array can be an array or an object. So I guess this should be fixed in the go-lib.

Will fix
